# Generated by Django 3.2.3 on 2021-06-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210603_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('info', 'danger'), ('warning', 'normal'), ('primary', 'low')], max_length=30),
        ),
    ]
